Wedding-Registry/Front

- .eslintrc
- package.json
- src/components/AdminLists.jsx
- src/pages/AdminAttendanceLists.jsx
- src/pages/AdminMain.jsx
- yarn.lock
관리 페이지 메인 기능 구현
1. 데이터 임시 적용 
2. 차트 그래프 적용
3. 참석 리스트 정렬 기능 적용
> [Feature/wedpro-21] 관리 페이지 메인 기능 구현

- src/App.jsx
- src/pages/GallerySupport.jsx
- src/pages/GalleryWedding.jsx
- src/pages/GoodsProduct.jsx
- src/pages/GoodsSupport.jsx
- src/pages/Layout.jsx
Reverts Wedding-Registry/Front#8
> Revert "merge test"

- package.json
- src/pages/AdminAttendanceLists.jsx
- yarn.lock
엑셀 파일 저장 기능 추가
- 엑셀 파일 저장 버튼(결혼식 참석여부 리스트 페이지)
- 임시 데이터 연결한 상태이므로 api 받아올 때 적용 필요
- api로직 적용할 때 다른 페이지에도 기능 넣을 예정
> [feature/wedpro-34] 엑셀 파일 저장

- .eslintrc
- index.html
- package.json
- src/App.jsx
- src/components/GalleryWeddingBox/GalleryWeddingBox.jsx
- src/components/modal/GalleryWeddingModal.jsx
- src/pages/GalleryWedding.jsx
- src/pages/GoodsProduct.jsx
- src/pages/styles.css
- yarn.lock
styles.css -> 웨딩 갤러리 페이지(결혼하는 사람) css 추후: css 폴더를 만들 예정
modal -> 웨딩갤러리모달은 웨딩 갤러리 페이지에서 박스 클릭 시 나오는 이미지 등록 box
> [design/WEDPRO-37] 웨딩 갤러리결혼하는사람 완료

- src/App.jsx
- src/components/ShareBox.jsx
- src/components/header/Header.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/main/MainContainer.jsx
- src/pages/main/MainPage.jsx
main page: 중간 이미지는 디자이너 협의해서 해결할 예정
main page: 중간 이미지 밑에 있는 곡선도 image로 대체할 예쩡
goodsproduct 수정: Layout 수정
> [design/WEDPRO-46] design: mainpage 1차완료

- src/App.jsx
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
navbar: 알림목록 icon 빼고 구현 완료
기능적인 부분은 추후 다시 할 예정
> [design/WEDPRO-47] design: navbar 1차 완료

- src/App.jsx
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/mocks/alarm.json
- src/mocks/handlers.js
navbar 구현 완료
현재 title은 text이지만 image로 변경
로그아웃 및 링크 공유 미 구현
> [feature/WEDPRO-49] feat: navbar msw get 완료

- src/components/box/Box.jsx
- src/components/goodsmodal/GoodsModal.jsx
- src/containers/admin/AdminMemoContainer.jsx
- src/containers/goods/GoodsProductContainer.jsx
modal 창 오픈 완료
현재 수정하기 | 삭제하기 기능 미 구현
> [design/WEDPRO-44] design: 상품등록 modal

- src/components/goodsmodal/GoodsModal.jsx
- src/constants/Api.js
- src/containers/goods/GoodsProductContainer.jsx
- src/mocks/handlers.js
fetch api 
constans api 파일로 분리
> [refac/WEDPRO-55] refac: api 파일 분리 및 test

- src/constants/Api.js
- src/containers/goods/GoodsSupportContainer.jsx
>  [feat/WEDPRO-56] feat: 상품후원페이지 완료

- src/components/box/Box.jsx
- src/containers/goods/GoodsProductContainer.jsx
> [design/WEDPRO-58] design: 상품 등록 페이지 디자인 수정

- src/containers/goods/GoodsProductContainer.jsx
상품등록 페이지 상품 아이템 분리 및 Api 2번 호출 막기
> [refac/WEDPRO-59] refac: 상품등록페이지 ITem refac

- src/components/navbar/Navbar.jsx
navbar list design 수정 및 Link to 작성
로그아웃 버튼 클릭 시 localStorage.removeItem('token')으로 일단 작성
>  [design/WEDPRO-60] design: navbar 디자인 변경

- src/components/goodsmodal/GoodsModal.jsx
- src/constants/Api.js
- src/containers/goods/GoodsProductContainer.jsx
> [design/WEDPRO-63] design: 상품등록 Modal 수정

- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/mocks/dummy.json
상품 등록 후원 페이지 bug 수정
사용자가 상품의 등록 갯수 5개이면 상품이 등록된 Box 컴포넌트가 5개 그리고 비어있는 5개가 보여야 하지만 상품이 등록된 Box 컴포넌트만 보이는 현상을 수정
> [fix/WEDPRO-69] fix: 상품 등록 후원페이지 수정

- src/apis/Api.js
- src/components/borderid/BorderIdModal.jsx
- src/containers/main/MainContainer.jsx
- src/pages/main/MainPage.jsx
- src/tokens/token.js
메인에서 게시판 id 생성하기 위한 modal 창 및 api 호출
그리고 token을 관리하는 함수 파일 하나 생성
> [feat/WEDPRO-76] feat: 메인 게시판id 생성

- src/components/borderid/BorderIdModal.jsx
- src/components/header/Header.jsx
> [feat/WEDPRO-77] feat: header icon에 따른 Link 처리

- src/apis/Api.js
- src/components/ShareBox.jsx
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/pages/goods/GoodsProduct.jsx
카카오톡 링크 공유 및 클립보스 복사 기능 완료
하지만 도메인이 나온 후 다시 테스트해야함
> [feat/WEDPRO-82] feat: 카카오톡링크 공유 및 클립보드 복사

- src/containers/goods/GoodsProductContainer.jsx
feat: 상품등록페이지 신랑,신부 정보 CRUD 완료
> [feat/WEDPRO-100] feat: 상품등록페이지 신랑,신부 정보 받아오기 완료

- src/apis/Api.js
- src/components/goodsmodal/GoodsModal.jsx
- src/containers/goods/GoodsProductContainer.jsx
> [feat/WEPDRO-101] feat: 상품 CRUD 완료

- src/App.jsx
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/containers/main/MainContainer.jsx
Guest로 입장했을때 Guest로 페이지 이동하는것이 아닌 결혼하는 사람 페이지로 이동하는것 막고
Guest 페이지로만 이동하게 만들기
> [feat/WEDPRO-102] feat: Guest로 입장했을때 Guest Page로 이동

- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/pages/goods/GoodsSupport.jsx
상품 후원 페이지에서 결혼하는 부부의 정보를 가져오지 못하는 버그 해결
> [fix/WEDPRO-104] fix: 상품 후원 페이지에서 부부 정보 버그 해결

- src/components/goodsmodal/GoodsModal.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
상품 수정 시 focus시 상품 수정 및 상품명 수정 초기화 되는 현상 수정
> [fix/WEDPRO-105] fix: 상품 수정 시 focus시 상품 수정 및 상품명 수정 초기화 되는 현상 수정

- src/apis/Api.js
- src/containers/goods/GoodsProductContainer.jsx
> [fix/WEDPRO-109] fix: 부부 정보 수정 시 갱신 되지 않는 현상

- src/containers/goods/GoodsProductContainer.jsx
>  [feat/WEDPRO-111] feat: 예식장 주소 저장 시 enter키 기능 추가

- src/components/navbar/Navbar.jsx
- src/components/signin/SignInForm.jsx
- src/components/signup/SignUpForm.jsx
- src/containers/main/MainContainer.jsx
사용자가 결혼하는사람이면 navbar에서 모든 리스트에 대한 값을 보여주지만
게스트인 경우 관리페이지와 위시리스트 그리고 알림 목록을 보여주지 않고 navbar 높이를 변경했음
>  [feat/WEDPRO-112] feat: 사용자에 따른 navbar ui 변경

- src/components/GalleryWeddingBox/GalleryWeddingBox.jsx
- src/components/navbar/Navbar.jsx
- src/components/signup/SignUpForm.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/containers/main/MainContainer.jsx
- src/pages/main/MainPage.jsx
Guest일때 로그아웃 했을때 현상 및 결혼하는사람 경로로 가는 버그 수정
> [fix/WEDPRO-113] fix: Guest일때 로그아웃 했을때 현상 및 결혼하는사람 경로로 가는 버그 수정

- src/apis/Api.js
- src/components/goodsmodal/GoodsModal.jsx
- src/components/goodssupportmodal/GoodsSupportModal.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
> [feat/WEDPRO-115] feat: 후원페이지 후원가 등록

- src/components/goodsmodal/GoodsModal.jsx
design: 후원가 수정 클릭 시 css 비정상적 움직임 현상 수정
> [design/WEDPRO-116] design: 후원가 수정 클릭 시 css 비정상적 움직임 현상 수정

- index.html
> [feat/WEPDRO-117] feat: 파비콘 및 웹 타이틀 설정

- src/apis/Api.js
- src/apis/HttpClient.js
api axios 호출 중복을 줄이고자 httpClient 파일 생성
>  [refac/WEDPRO-118] refac: HttpClient 생성

- .eslintrc
- src/main.jsx
- src/repository/AuthTokenRepository.js
> [refac/WEDPRO-120] refac: 로그인후  token 핸들링하는 로직

- src/App.jsx
- src/apis/Api.js
- src/apis/HttpClient.js
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/main.jsx
- src/repository/AuthTokenRepository.js
- src/services/navbar/NavbarService.js
navbar api 호출 할때 계쏙 token값을 매개변수로 보내줘야했지만 httpclient를 통해 이제 token을 보내줄 필요가없다.
> [refac/WEDPRO-121] refac: navbar api 호출 refac

- src/components/borderid/BorderIdModal.jsx
- src/containers/main/MainContainer.jsx
- src/hooks/useTokenDecode.jsx
- src/pages/main/MainPage.jsx
- src/services/goods/GoodsProductService.js
boderId생성하는 borderModal api 분리
> [refac/WEDPRO-122] refac: borderId api 분리

- src/apis/Api.js
- src/apis/HttpClient.js
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/components/signin/SignInForm.jsx
- src/containers/main/MainContainer.jsx
- src/repository/AuthTokenRepository.js
- src/services/goods/GoodsProductService.js
- src/services/navbar/NavbarService.js
api 호출하는 단계에서 localstorage 토큰값이 필요함에 따라  전역적으로 관리하고 token을 불러오는 코드를 적게 사용하기 위해 interceptors를 활용하여 api 호출하도록 리팩토링 진행
> refac/WEDPRO-123] refac: httpclient interceptors를 활용하여 api 호출 하기

- src/components/header/Header.jsx
- src/services/goods/GoodsMarriedService.js
- src/services/goods/GoodsProductService.js
apis.js 파일에 모든 api가 존재하는데 상품 등록 페이지에 있는 api를 결혼 부부 와 상품 으로  각각 service 폴더에 분리
>  [refac/WEDPRO-124] refac: 상품 등록 페이지 api 분리

- src/apis/HttpClient.js
- src/components/goodsmodal/GoodsModal.jsx
- src/components/navbar/Navbar.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/mocks/handlers.js
- src/pages/goods/GoodsProduct.jsx
- src/services/goods/GoodsMarriedService.js
- src/services/goods/GoodsProductService.js
apis 폴더에 있는 상품 등록 api Service 폴더로 분리 및 상품 등록 페이지 api 호출할때마다 들어가는 토큰 중복 코드 삭제 및 api 호출 코드 변경
> [refac/WEDPRO-125] refac: 상품 등록 페이지 api 분리

- src/apis/HttpClient.js
- src/components/goodssupportmodal/GoodsSupportModal.jsx
- src/components/navbar/Navbar.jsx
- src/components/radiobutton/RadioButtonGroup.jsx
- src/containers/gallery/GallerySupportContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/pages/goods/GoodsSupport.jsx
- src/repository/GuestAuthTokenRepository.js
- src/services/gustGoods/GuestGoodsProductSerivce.js
- src/services/gustGoods/GuestMarriedService.js
상품 후원 페이지 api 분리및 라디오버튼 group 컴포넌트 분리
> [refac/WEDPRO-128] refac: 상품 후원 페이지 api 분리및 라디오버튼 group 컴포넌트 분리

- src/containers/gallery/GallerySupportContainer.jsx
- src/containers/gallery/GalleryWeddingContainer.jsx
- src/pages/gallery/GallerySupport.jsx
- src/services/guestWedding/GuestWeddungImgSerivce.js
>  [refac/WEDPRO-129] refac: 웨딩 갤러리 후원 페이지 api 분리

- src/components/ShareBox.jsx
- src/components/navbar/Navbar.jsx
- src/services/goods/GoodsMarriedService.js
- src/services/uuid/UrlUuidService.js
> [refac/WEDPRO-130] refac: uuid api 분리

- src/components/goodsmodal/GoodsModal.jsx
> [design/WEDPRO-135] design: 상품 등록 Modal 배경 투명도 없애기

- src/components/navbar/Navbar.jsx
useDecodeToken 커스텀 훅에 token을 보내주주 않아 생기는 오류
> [fix/WEDPRO-136] fix: useDecodeToken 커스텀 훅에 token을 보내주주 않아 생기는 오류

- src/components/goodsmodal/GoodsModal.jsx
- src/services/goods/GoodsProductService.js
상품 등록 시 잘못된 url 정보 사용자에게 alert 보여주고 url input text 초기화 시키기
> [feat/WEDPRO-138] feat:상품 등록 시 잘못된 url 정보 보여주고 url input 초기화 시키기

- src/containers/goods/GoodsProductContainer.jsx
> [feat/WEDPRO-139] feat: 부부의 정보 api 상태에 따른 검증

- src/containers/goods/GoodsProductContainer.jsx
> [feat/WEDPRO-140] feat: 예식장 및 예식날짜 저장에 따른 alert 처리

- src/components/goodssupportmodal/GoodsSupportModal.jsx
- src/containers/goods/GoodsProductContainer.jsx
이미 후원한 상품은 다시 후원할 수 없다는 alert 처리
> [fix/WEDRPO-141] fix: 이미 후원한 상품은 다시 후원할 수 없다는 alert 처리

- src/components/ShareBox.jsx
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/containers/gallery/GallerySupportContainer.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/state/uuidState.js
Guest에서 로고 클릭 시 결혼하는 사람 상태로 바뀌는 현상 수정
> [fix/WEDPRO-142] fix: Guest에서 로고 클릭 시 결혼하는 사람 상태로 바뀌는 현상 수정

- src/components/goodssupportmodal/GoodsSupportModal.jsx
- src/components/navbar/Navbar.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/pages/gallery/GallerySupport.jsx
Guest 에서 후원할 때 다른사람의 총  후원금액이 보이는 현상 수정
guest 에서 navbar를 이용한 페이지 이동 버그 수정
>  [feat:WEDPRO-143] feat: Guest 에서 후원할 때 다른사람의 총  후원금액이 보이는 현상 수정

- src/components/GalleryWeddingBox/GalleryWeddingBox.jsx
- src/containers/gallery/GalleryWeddingContainer.jsx
> [design/WEDPRO-145] design: 웨딩 갤러리 삭제 아이콘 위치 조정

- src/components/ShareBox.jsx
- src/components/navbar/Navbar.jsx
> [feat/WEDPRO-146] feat: 카카오톡 공유하기 완료

- .github/workflows/CI/CD.yml
- package.json
> [CHORE/WEDPRO-147] CHORE: aws s3 ci/cd 배포

- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
> [fix/WEDPRO-149] fix: navbar 유저 상태에 따른 처리

- src/components/ShareBox.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/state/marriedInformationState.js
카카오톡 공유하기 설명 신랑 신부 이름으로 바꿔서 공유하기
> [feat/WEDPRO-151] feat: 카카오톡 공유하기 설명 신랑 신부 이름으로 바꿔서 공유하기

- package.json
> [fix/WEDPRO-156] fix: env 파일 인식 error

- package.json
- src/components/goodsmodal/GoodsModal.jsx
- src/components/goodssupportmodal/GoodsSupportModal.jsx
> [feat/WEDPRO-157] feat: enter키 누를 시 상품 등록 됨

- package.json
> [fix/WEDPRO-159] fix: github actions env-cmd error

- package.json
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
Gust 예식장 text 길이 및 위치 조정
Guest 예식 날짜 및 시간 수정
> [design/WEDPRO-160] design: Gust 예식장 text 길이 및 위치 조정

- src/components/ShareBox.jsx
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/repository/GuestUuidRespository.js
uuid localstorage 저장 후 상태 판별하기
> [feat/WEDPRO-161] feat: uuid localstorage 저장 후 상태 판별하기

- package.json
- src/components/GalleryWeddingBox/GalleryWeddingBox.jsx
- src/components/navbar/Navbar.jsx
- src/containers/gallery/GallerySupportContainer.jsx
- src/containers/gallery/GalleryWeddingContainer.jsx
- yarn.lock
> [feat/WEDPRO-162] feat: 상품 이미지 등록 시 버튼 크기 확장하기

- package.json
- yarn.lock
> [fix/WEDPRO-163] fix: env-cmd로 env파일 정의해보기

- index.css
- package.json
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/services/goods/GoodsMarriedService.js
- yarn.lock
> [feat/WEDPRO-164] feat: date-picker 기능 구현

- src/components/goodsmodal/GoodsModal.jsx
- src/components/goodssupportmodal/GoodsSupportModal.jsx
> [design/WEDPRO-165] design: 등록하기 버튼 및 후원 :  수정

- src/components/navbar/Navbar.jsx
> [feat/WEDPRO-166] feat: navbar 결혼식 참석 여부 알림 변경

- src/components/datetimePicker/DateTimePeicker.jsx
- src/components/goodssupportmodal/GoodsSupportModal.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/hooks/useDateTImeConver.jsx
- src/hooks/useDateTimeFormat.jsx
- src/state/datePickerState.js
refac: DateTimePicker 공통 컴포넌트 분리 및 datetimeformat custom hook으로 생성
> [refac/WEDPRO-167] refac: DateTimePicker 공통 컴포넌트 분리 및 datetimeformat custom hook으로 생성

- src/components/sharebox/ShareBox.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/util/shareKaKaoLink.js
> [refac/WEDPRO-168] refac: 카카오공유하기 버튼 분리

- src/components/goodsElementList/GoodsElementList.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
상품 등록 목록에서 상품이 등록되어 있지 않은 상품 등록 목록 Box 분리
> [refac/WEDPRO-169] refac: GoodsElementList 분리

- src/App.jsx
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
> [refac/WEPDRO-170] refac: navbar 상태 수정

- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
상품 후원 게이지 100% 넘길 시 100%에서 넘치지 않도록 수정
> [feat/WEDPRO-171] feat: 상품 후원 게이지 100% 넘길 시 100%에서 넘치지 않도록 수정

- src/containers/goods/GoodsProductContainer.jsx
예식장 주소 enter가 아닌 영역 밖 클릭 했을때 api 저장
> [feat/WEDPRO-174] feat: 예식장 주소 enter가 아닌 영역 밖 클릭 했을때 api 저장

- src/components/datetimePicker/DateTimePeicker.jsx
- src/containers/goods/GoodsProductContainer.jsx
> [design/WEDPRO-175] design: 예식 날짜 placeholder

- src/components/navbar/Navbar.jsx
로그인 상태에 따른 navbar login logout 관리 및 로그인 진행해주세요 로그인 이동
> [feat/WEDPRO-176] feat: 로그인 상태에 따른 navbar login logout 관리 

- src/components/goodsmodal/GoodsModal.jsx
- src/components/goodssupportmodal/GoodsSupportModal.jsx
- src/components/navbar/Navbar.jsx
- src/containers/main/MainContainer.jsx
메인페이지 라운드 위치 및 상품 등록 modal 디자인 변경
> [design/WEDPRO-177] 메인페이지 라운드 위치 및 상품 등록 modal 디자인 변경

- src/components/goodsmodal/GoodsModal.jsx
design: 상품 등록 상태에 따른 버튼 활성화 관리
> [desgin/WEDPRO-178] design: 상품 등록 상태에 따른 버튼 활성화 관리

- src/containers/goods/GoodsProductContainer.jsx
> [feat/WEDPRO-179] feat: 예식장 주소 저장 버튼 생성

- src/components/sharebox/ShareBox.jsx
- src/containers/goods/GoodsProductContainer.jsx
> 클립보드 api os에따라 안되는 사항 수정

- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/containers/gallery/GallerySupportContainer.jsx
>  feat: 유저 상태에 따른 navbar 수정

- src/components/GalleryWeddingBox/GalleryWeddingBox.jsx
- src/components/header/Header.jsx
- src/components/imageSilder/ImageSilder.jsx
- src/components/navbar/Navbar.jsx
- src/containers/gallery/GallerySupportContainer.jsx
- src/containers/gallery/GalleryWeddingContainer.jsx
> [refac/WEDPRO-183] refac: 이미지 슬라이더 컴포넌트로 분리

- src/components/goodsmodal/GoodsModal.jsx
- src/components/header/Header.jsx
- src/components/navbar/Navbar.jsx
- src/containers/goods/GoodsProductContainer.jsx
- src/containers/goods/GoodsSupportContainer.jsx
- src/containers/main/MainContainer.jsx
- src/services/goods/GoodsProductService.js
> [design/WEDPRO-185] desgin: 메인 페이지 및 navbar 알림 목록
